version: '3.7'
services:
  topsymbols:
    build:
      context: ../../../
      dockerfile: ./src/main/docker/Dockerfile.jvm
    image: topsymbols
    container_name: topsymbols
    env_file: ../../../.env
    depends_on:
      - postgres
    ports:
      - 8080:8080
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    depends_on:
      - topsymbols
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  postgres:
    image:  postgres:11.3
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER : "topsymbol"
      POSTGRES_PASSWORD : "topsymbol"
      POSTGRES_DB : "topsymbol_db"
