name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '13'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew test --tests '*top*'
        env:
          BINANCE_SECRET_APIKEY: ${{github.BINANCE_SECRET_APIKEY}}
